rdp_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
    cpu: 4
    memory: 8G

  timeout_in: 3600m

  configure_rdp_script:
    - powershell -Command "Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name fDenyTSConnections -Value 0 -Force"
    - powershell -Command "Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name UserAuthentication -Value 0 -Force"
    - powershell -Command "Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name SecurityLayer -Value 0 -Force"
    - powershell -Command "netsh advfirewall firewall add rule name='RDP' dir=in action=allow protocol=TCP localport=3389"
    - powershell -Command "Restart-Service -Name TermService -Force"

  create_user_script:
    - powershell -Command "$pass = ConvertTo-SecureString 'MiPassword123!' -AsPlainText -Force; New-LocalUser -Name RDP -Password $pass -AccountNeverExpires"
    - powershell -Command "Add-LocalGroupMember -Group Administrators -Member RDP"
    - powershell -Command "Add-LocalGroupMember -Group 'Remote Desktop Users' -Member RDP"

  install_tailscale_script:
    - powershell -Command "Invoke-WebRequest -Uri https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi -OutFile $env:TEMP\tailscale.msi"
    - powershell -Command "Start-Process msiexec.exe -ArgumentList '/i', \"$env:TEMP\tailscale.msi\", '/quiet', '/norestart' -Wait"

  connect_tailscale_script:
    - powershell -Command "& '$env:ProgramFiles\Tailscale\tailscale.exe' up --authkey=%TAILSCALE_AUTH_KEY% --hostname=cirrus-%CIRRUS_TASK_ID%"
    - powershell -Command "$ip = & '$env:ProgramFiles\Tailscale\tailscale.exe' ip -4; Write-Host '=== TAILSCALE IP:' $ip '==='"

  keep_alive_script:
    - powershell -Command "while($true){ Write-Host \"[$(Get-Date)] Activo...\"; Start-Sleep 300 }"
