rdp_task:
  env:
    TAILSCALE_AUTH_KEY: ENCRYPTED[!db631b422df30e8e6376ed3ba6e1858778c3ac598ef620d31c64297cea09669d97ffdc47ccef486dc6229d8f95e5965b!]

  windows_container:
    image: cirrusci/windowsservercore:2019
    cpu: 2
    memory: 4G

  timeout_in: 3600m

  configure_rdp_script:
    - powershell -Command "Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name fDenyTSConnections -Value 0 -Force"
    - powershell -Command "Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name UserAuthentication -Value 0 -Force"
    - powershell -Command "Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name SecurityLayer -Value 0 -Force"
    - powershell -Command "Restart-Service -Name TermService -Force"

  create_user_script:
    - powershell -Command "$pass = ConvertTo-SecureString 'Arma654456qweqwe@@@' -AsPlainText -Force; New-LocalUser -Name RDP -Password $pass -AccountNeverExpires"
    - powershell -Command "Add-LocalGroupMember -Group Administrators -Member RDP"
    - powershell -Command "Add-LocalGroupMember -Group 'Remote Desktop Users' -Member RDP"

  install_tailscale_script:
    - powershell -Command "Invoke-WebRequest -Uri https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi -OutFile $env:TEMP\tailscale.msi"
    - powershell -Command "Start-Process msiexec.exe -ArgumentList '/i','$env:TEMP\tailscale.msi','/quiet','/norestart' -Wait"

  connect_tailscale_script:
    - powershell -Command "& '$env:ProgramFiles\Tailscale\tailscale.exe' up --authkey=$env:TAILSCALE_AUTH_KEY --hostname=cirrus-$env:CIRRUS_TASK_ID"
    - powershell -Command "$ip = & '$env:ProgramFiles\Tailscale\tailscale.exe' ip -4; Write-Host TAILSCALE_IP $ip"

  keep_alive_script:
    - powershell -Command "while($true){ Write-Host Activo; Start-Sleep 300 }"
